spring.application.name=Comforent

# Datasource
spring.datasource.url=ENC(YxnA6ZWvY7/4jzDlLWjIrBPeCuHAWk1iHl3ztvQuQGXlPh5QsdSA3aEK7+DE9CwHJ9+lrxvmPhyT+/3JFelHpMN3Z9KZLnYAOrD993mVAms=)
spring.datasource.username=ENC(rgeaDtpdAe3Zz3hYI+GWxp9MATv5et8SiNYfPnjo+nWaQ6ITmgY2kLhbgPAGQHM/)
spring.datasource.password=ENC(MTAfA393Z6p72f+CbjAfEg9ZRqEcAjbKmt4mzv+QL1JbVlGE1HgjVNz05DG8G7HY)
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Jasypt
jasypt.encryptor.password=${JASYPT_ENCRYPTOR_PASSWORD}

# Docker
spring.docker.compose.enabled=false

# jwt
jwt.secret=ENC(goNBpXLAh6lXeEvXmN4WBUXS7W6B6OLJRbxGlhg3OYUHJdXG9ue+6VV1rWLvty9p/xqYnAWJnKDs8RH+GzPr5jp04EaFdRlb6YPmsi9Inyk=)
# 1 day
jwt.expiration=86400000

# Liquibase
spring.liquibase.url=ENC(YxnA6ZWvY7/4jzDlLWjIrBPeCuHAWk1iHl3ztvQuQGXlPh5QsdSA3aEK7+DE9CwHJ9+lrxvmPhyT+/3JFelHpMN3Z9KZLnYAOrD993mVAms=)
spring.liquibase.user=ENC(rgeaDtpdAe3Zz3hYI+GWxp9MATv5et8SiNYfPnjo+nWaQ6ITmgY2kLhbgPAGQHM/)
spring.liquibase.password=ENC(MTAfA393Z6p72f+CbjAfEg9ZRqEcAjbKmt4mzv+QL1JbVlGE1HgjVNz05DG8G7HY)
spring.liquibase.change-log=classpath:/db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true
logging.level.liquibase=DEBUG

# Cloudflare
cloudflare.r2.public-url=ENC(BBPAmvw9HIr/S5a8/nG+LVRw7L0ger22M2S8Q5c0a9ihwWEqeZtlEn8GBk7S2xE1pYrQhIY6so18Kx2j/UAlBjidz/QtG7WccFe+//etvM5rvKs3DgczD9qeHuHxC1+T)
cloudflare.r2.endpoint=ENC(/ULZZUDsrdLChcEgLQ20hKqTvsOH1XfnARyIvml0fjIaq4TaOQoxakO6ASpoGGTk5CDX5DDm+uuAX+fJCu6NtOyZtC2v75NHtjxHlblKmyJdQoYLrUyS5xbh7PcZJrjNVpKXBBE69f5AUgyw9Yasow==)
cloudflare.r2.accessKey=ENC(Kp8cIw0R9kn19lKWm60lmtl12w8CqZ0TXq76Fz563z5QZKFEmYbrLKrzm/EDsS63UlaQakaB73kjsFdnJHZ+wjPZyY/9GvwKaLr9Oa/SnSI=)
cloudflare.r2.secretKey=ENC(ppr0eAxes2NhzkoWMxHkcZebQIPXbDzdh57gpWf+bDcI0r13njKqXJIQcSLm+ivxMRVoBcQYa4vsk10FETTPKFTVhsffrYeXcR2tyB56MEr8uul2VnVTxo9l/OoTMl8P2UWNGQiQjF48lqSqMPgnaA==)
cloudflare.r2.bucket=comforent-images

# MultipartFile
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

spring.jpa.show-sql=true

# OAuth2 - Google
spring.security.oauth2.client.registration.google.client-id=ENC(ih9yJYh7kdRNddwetPcC/0LRKgizT5v0Rc+IsQhfNpElCZr3+z9pwvrGscjGVWUKXoUU/AQTZ3AmRChh0CWYwxWlFvcMBpYaXhg5YMhvidJvqUdGKs/Lqv5o5aRIHTWXjYUSh3/5uS18qRCnMLgNEw==)
spring.security.oauth2.client.registration.google.client-secret=ENC(/kId1RHL6wcF915uqBP5yA+gyhIL7X7VUa934m97Xy8y2CJdnVPZJVukfug6I66MvLpM4LDLFnsChArGMJZjn+5qgr4NgvVkhCCtbY8RYlc=)
spring.security.oauth2.client.registration.google.scope=email,profile

spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo

spring.security.oauth2.client.error-uri=/oauth2/error
oauth2.error.default=OAuth2 authorization failed

app.frontend.url=http://localhost:3000
app.frontend.oauth2.error-path=/oauth2/error

oauth2.error.constraint.violation=???????????? ?????? ???????????? ?? Google. ????????, ??? ??? ??????? ?? ????????????? ???????????.
oauth2.error.generic=????????? ?????? ??? ??????????? ????? Google.
